language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
jdk:
  - oraclejdk8
script:
  - ./gradlew
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
  - bash <(curl -s https://codecov.io/bash)
